repos:
  - repo: local
    hooks:
      - id: api
        entry: bash -c "cd ./api && black ./"
        language: system
        name: api
        verbose: true
      - id: app
        entry: bash -c "cd ./app && pnpm chore:lint"
        language: system
        name: app
        verbose: true
      - id: notebook
        entry: bash -c "cd ./notebook && black ./"
        language: system
        name: notebook
        verbose: true
