name: status

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: sh ./scripts/install.sh
        shell: bash

      - run: sh ./scripts/lint.sh
        shell: bash
